// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"libri/ent/book"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BookCreate is the builder for creating a Book entity.
type BookCreate struct {
	config
	mutation *BookMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetIsbn sets the "isbn" field.
func (_c *BookCreate) SetIsbn(v string) *BookCreate {
	_c.mutation.SetIsbn(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *BookCreate) SetTitle(v string) *BookCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetAuthors sets the "authors" field.
func (_c *BookCreate) SetAuthors(v []string) *BookCreate {
	_c.mutation.SetAuthors(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *BookCreate) SetURL(v string) *BookCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetSourcePriority sets the "source_priority" field.
func (_c *BookCreate) SetSourcePriority(v int) *BookCreate {
	_c.mutation.SetSourcePriority(v)
	return _c
}

// SetNillableSourcePriority sets the "source_priority" field if the given value is not nil.
func (_c *BookCreate) SetNillableSourcePriority(v *int) *BookCreate {
	if v != nil {
		_c.SetSourcePriority(*v)
	}
	return _c
}

// SetSourceName sets the "source_name" field.
func (_c *BookCreate) SetSourceName(v string) *BookCreate {
	_c.mutation.SetSourceName(v)
	return _c
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_c *BookCreate) SetNillableSourceName(v *string) *BookCreate {
	if v != nil {
		_c.SetSourceName(*v)
	}
	return _c
}

// Mutation returns the BookMutation object of the builder.
func (_c *BookCreate) Mutation() *BookMutation {
	return _c.mutation
}

// Save creates the Book in the database.
func (_c *BookCreate) Save(ctx context.Context) (*Book, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BookCreate) SaveX(ctx context.Context) *Book {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BookCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BookCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BookCreate) defaults() {
	if _, ok := _c.mutation.SourcePriority(); !ok {
		v := book.DefaultSourcePriority
		_c.mutation.SetSourcePriority(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BookCreate) check() error {
	if _, ok := _c.mutation.Isbn(); !ok {
		return &ValidationError{Name: "isbn", err: errors.New(`ent: missing required field "Book.isbn"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Book.title"`)}
	}
	if _, ok := _c.mutation.Authors(); !ok {
		return &ValidationError{Name: "authors", err: errors.New(`ent: missing required field "Book.authors"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Book.url"`)}
	}
	if _, ok := _c.mutation.SourcePriority(); !ok {
		return &ValidationError{Name: "source_priority", err: errors.New(`ent: missing required field "Book.source_priority"`)}
	}
	return nil
}

func (_c *BookCreate) sqlSave(ctx context.Context) (*Book, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BookCreate) createSpec() (*Book, *sqlgraph.CreateSpec) {
	var (
		_node = &Book{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(book.Table, sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Isbn(); ok {
		_spec.SetField(book.FieldIsbn, field.TypeString, value)
		_node.Isbn = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(book.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Authors(); ok {
		_spec.SetField(book.FieldAuthors, field.TypeJSON, value)
		_node.Authors = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(book.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.SourcePriority(); ok {
		_spec.SetField(book.FieldSourcePriority, field.TypeInt, value)
		_node.SourcePriority = value
	}
	if value, ok := _c.mutation.SourceName(); ok {
		_spec.SetField(book.FieldSourceName, field.TypeString, value)
		_node.SourceName = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Book.Create().
//		SetIsbn(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BookUpsert) {
//			SetIsbn(v+v).
//		}).
//		Exec(ctx)
func (_c *BookCreate) OnConflict(opts ...sql.ConflictOption) *BookUpsertOne {
	_c.conflict = opts
	return &BookUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Book.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BookCreate) OnConflictColumns(columns ...string) *BookUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BookUpsertOne{
		create: _c,
	}
}

type (
	// BookUpsertOne is the builder for "upsert"-ing
	//  one Book node.
	BookUpsertOne struct {
		create *BookCreate
	}

	// BookUpsert is the "OnConflict" setter.
	BookUpsert struct {
		*sql.UpdateSet
	}
)

// SetIsbn sets the "isbn" field.
func (u *BookUpsert) SetIsbn(v string) *BookUpsert {
	u.Set(book.FieldIsbn, v)
	return u
}

// UpdateIsbn sets the "isbn" field to the value that was provided on create.
func (u *BookUpsert) UpdateIsbn() *BookUpsert {
	u.SetExcluded(book.FieldIsbn)
	return u
}

// SetTitle sets the "title" field.
func (u *BookUpsert) SetTitle(v string) *BookUpsert {
	u.Set(book.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BookUpsert) UpdateTitle() *BookUpsert {
	u.SetExcluded(book.FieldTitle)
	return u
}

// SetAuthors sets the "authors" field.
func (u *BookUpsert) SetAuthors(v []string) *BookUpsert {
	u.Set(book.FieldAuthors, v)
	return u
}

// UpdateAuthors sets the "authors" field to the value that was provided on create.
func (u *BookUpsert) UpdateAuthors() *BookUpsert {
	u.SetExcluded(book.FieldAuthors)
	return u
}

// SetURL sets the "url" field.
func (u *BookUpsert) SetURL(v string) *BookUpsert {
	u.Set(book.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *BookUpsert) UpdateURL() *BookUpsert {
	u.SetExcluded(book.FieldURL)
	return u
}

// SetSourcePriority sets the "source_priority" field.
func (u *BookUpsert) SetSourcePriority(v int) *BookUpsert {
	u.Set(book.FieldSourcePriority, v)
	return u
}

// UpdateSourcePriority sets the "source_priority" field to the value that was provided on create.
func (u *BookUpsert) UpdateSourcePriority() *BookUpsert {
	u.SetExcluded(book.FieldSourcePriority)
	return u
}

// AddSourcePriority adds v to the "source_priority" field.
func (u *BookUpsert) AddSourcePriority(v int) *BookUpsert {
	u.Add(book.FieldSourcePriority, v)
	return u
}

// SetSourceName sets the "source_name" field.
func (u *BookUpsert) SetSourceName(v string) *BookUpsert {
	u.Set(book.FieldSourceName, v)
	return u
}

// UpdateSourceName sets the "source_name" field to the value that was provided on create.
func (u *BookUpsert) UpdateSourceName() *BookUpsert {
	u.SetExcluded(book.FieldSourceName)
	return u
}

// ClearSourceName clears the value of the "source_name" field.
func (u *BookUpsert) ClearSourceName() *BookUpsert {
	u.SetNull(book.FieldSourceName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Book.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BookUpsertOne) UpdateNewValues() *BookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Book.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BookUpsertOne) Ignore() *BookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BookUpsertOne) DoNothing() *BookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BookCreate.OnConflict
// documentation for more info.
func (u *BookUpsertOne) Update(set func(*BookUpsert)) *BookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BookUpsert{UpdateSet: update})
	}))
	return u
}

// SetIsbn sets the "isbn" field.
func (u *BookUpsertOne) SetIsbn(v string) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetIsbn(v)
	})
}

// UpdateIsbn sets the "isbn" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateIsbn() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateIsbn()
	})
}

// SetTitle sets the "title" field.
func (u *BookUpsertOne) SetTitle(v string) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateTitle() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateTitle()
	})
}

// SetAuthors sets the "authors" field.
func (u *BookUpsertOne) SetAuthors(v []string) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetAuthors(v)
	})
}

// UpdateAuthors sets the "authors" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateAuthors() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateAuthors()
	})
}

// SetURL sets the "url" field.
func (u *BookUpsertOne) SetURL(v string) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateURL() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateURL()
	})
}

// SetSourcePriority sets the "source_priority" field.
func (u *BookUpsertOne) SetSourcePriority(v int) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetSourcePriority(v)
	})
}

// AddSourcePriority adds v to the "source_priority" field.
func (u *BookUpsertOne) AddSourcePriority(v int) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.AddSourcePriority(v)
	})
}

// UpdateSourcePriority sets the "source_priority" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateSourcePriority() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateSourcePriority()
	})
}

// SetSourceName sets the "source_name" field.
func (u *BookUpsertOne) SetSourceName(v string) *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.SetSourceName(v)
	})
}

// UpdateSourceName sets the "source_name" field to the value that was provided on create.
func (u *BookUpsertOne) UpdateSourceName() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.UpdateSourceName()
	})
}

// ClearSourceName clears the value of the "source_name" field.
func (u *BookUpsertOne) ClearSourceName() *BookUpsertOne {
	return u.Update(func(s *BookUpsert) {
		s.ClearSourceName()
	})
}

// Exec executes the query.
func (u *BookUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BookCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BookUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BookUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BookUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BookCreateBulk is the builder for creating many Book entities in bulk.
type BookCreateBulk struct {
	config
	err      error
	builders []*BookCreate
	conflict []sql.ConflictOption
}

// Save creates the Book entities in the database.
func (_c *BookCreateBulk) Save(ctx context.Context) ([]*Book, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Book, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BookMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BookCreateBulk) SaveX(ctx context.Context) []*Book {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BookCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BookCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Book.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BookUpsert) {
//			SetIsbn(v+v).
//		}).
//		Exec(ctx)
func (_c *BookCreateBulk) OnConflict(opts ...sql.ConflictOption) *BookUpsertBulk {
	_c.conflict = opts
	return &BookUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Book.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BookCreateBulk) OnConflictColumns(columns ...string) *BookUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BookUpsertBulk{
		create: _c,
	}
}

// BookUpsertBulk is the builder for "upsert"-ing
// a bulk of Book nodes.
type BookUpsertBulk struct {
	create *BookCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Book.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BookUpsertBulk) UpdateNewValues() *BookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Book.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BookUpsertBulk) Ignore() *BookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BookUpsertBulk) DoNothing() *BookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BookCreateBulk.OnConflict
// documentation for more info.
func (u *BookUpsertBulk) Update(set func(*BookUpsert)) *BookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BookUpsert{UpdateSet: update})
	}))
	return u
}

// SetIsbn sets the "isbn" field.
func (u *BookUpsertBulk) SetIsbn(v string) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetIsbn(v)
	})
}

// UpdateIsbn sets the "isbn" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateIsbn() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateIsbn()
	})
}

// SetTitle sets the "title" field.
func (u *BookUpsertBulk) SetTitle(v string) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateTitle() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateTitle()
	})
}

// SetAuthors sets the "authors" field.
func (u *BookUpsertBulk) SetAuthors(v []string) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetAuthors(v)
	})
}

// UpdateAuthors sets the "authors" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateAuthors() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateAuthors()
	})
}

// SetURL sets the "url" field.
func (u *BookUpsertBulk) SetURL(v string) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateURL() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateURL()
	})
}

// SetSourcePriority sets the "source_priority" field.
func (u *BookUpsertBulk) SetSourcePriority(v int) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetSourcePriority(v)
	})
}

// AddSourcePriority adds v to the "source_priority" field.
func (u *BookUpsertBulk) AddSourcePriority(v int) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.AddSourcePriority(v)
	})
}

// UpdateSourcePriority sets the "source_priority" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateSourcePriority() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateSourcePriority()
	})
}

// SetSourceName sets the "source_name" field.
func (u *BookUpsertBulk) SetSourceName(v string) *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.SetSourceName(v)
	})
}

// UpdateSourceName sets the "source_name" field to the value that was provided on create.
func (u *BookUpsertBulk) UpdateSourceName() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.UpdateSourceName()
	})
}

// ClearSourceName clears the value of the "source_name" field.
func (u *BookUpsertBulk) ClearSourceName() *BookUpsertBulk {
	return u.Update(func(s *BookUpsert) {
		s.ClearSourceName()
	})
}

// Exec executes the query.
func (u *BookUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BookCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BookCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BookUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
