-- Create "books" table
CREATE TABLE "public"."books" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "isbn" character varying NOT NULL,
  "title" character varying NOT NULL,
  "authors" jsonb NOT NULL,
  "url" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "books_isbn_key" to table: "books"
CREATE UNIQUE INDEX "books_isbn_key" ON "public"."books" ("isbn");
